CREATE TABLE customer (C_CUSTKEY INTEGER, C_NAME VARCHAR(25),C_ADDRESS VARCHAR(40),C_NATIONKEY INTEGER, C_PHONE CHAR(15),C_ACCTBAL FLOAT(8),C_MKTSEGMENT CHAR(10),C_COMMENT VARCHAR(117));
CREATE TABLE lineitem (L_ORDERKEY INTEGER, L_PARTKEY INTEGER,L_SUPPKEY INTEGER,L_LINENUMBER INTEGER,L_QUANTITY FLOAT(8));
CREATE TABLE orders (O_ORDERKEY INTEGER,O_CUSTKEY INTEGER,O_ORDERSTATUS CHAR(1),O_TOTALPRICE FLOAT(8),O_ORDERDATE DATE,O_ORDERPRIORITY CHAR(15),O_CLERK CHAR(15), O_SHIPPIORITY INTEGER, O_COMMENT VARCHAR(79));
CREATE TABLE part (P_PARTKEY INTEGER,P_NAME VARCHAR(55),P_MFGR CHAR 25 P_BRAND CHAR 10 P_TYPE VARCHAR 25 P_SIZE INTEGER 8 P_CONTAINER CHAR 10 P_RETAILPRICE FLOAT 8 P_COMMENT VARCHAR 23);

CREATE TABLE nation (N_NATIONKEY INTEGER, N_NAME CHAR(25),N_REGIONKEY INTEGER,N_COMMENT VARCHAR(152));

CREATE TABLE region (R_REGIONKEY INTEGER, R_NAME CHAR(25),R_COMMENT VARCHAR(152));
CREATE TABLE supplier (S_SUPPKEY INTEGER,  S_NAME CHAR(25), S_ADDRESS VARCHAR(40),S_NATIONKEY INTEGER, S_PHONE CHAR(15),S_ACCTBAL FLOAT(8),S_COMMENT VARCHAR(101));

LOAD 'nation.tbl' INTO nation;
LOAD 'region.tbl' INTO region;
