C_CUSTKEY INTEGER 8 C_NAME VARCHAR 25 C_ADDRESS VARCHAR 40 C_NATIONKEY INTEGER 8 C_PHONE CHAR 15 C_ACCTBAL FLOAT 8 C_MKTSEGMENT CHAR 10 C_COMMENT VARCHAR 117

CREATE TABLE CUSTOMER (C_CUSTKEY INTEGER, C_NAME VARCHAR(25),C_ADDRESS VARCHAR(40))